// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHLDFhUhrAdcb3O7nxcNNbXiIjXLon_wk',
    appId: '1:605908013775:web:174438737fbb34a575ddba',
    messagingSenderId: '605908013775',
    projectId: 'prime-art-eab7d',
    authDomain: 'prime-art-eab7d.firebaseapp.com',
    storageBucket: 'prime-art-eab7d.firebasestorage.app',
    measurementId: 'G-EYV3X52B6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6d--JvMYDxp-WSbnm_FSSwP4rsqZ6x4',
    appId: '1:605908013775:android:2bc7c5ff270ae1d675ddba',
    messagingSenderId: '605908013775',
    projectId: 'prime-art-eab7d',
    storageBucket: 'prime-art-eab7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClHODWmGr-tfRpPf3vyRn3rzhU6Zf5F5M',
    appId: '1:605908013775:ios:37c444f142127b1d75ddba',
    messagingSenderId: '605908013775',
    projectId: 'prime-art-eab7d',
    storageBucket: 'prime-art-eab7d.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClHODWmGr-tfRpPf3vyRn3rzhU6Zf5F5M',
    appId: '1:605908013775:ios:37c444f142127b1d75ddba',
    messagingSenderId: '605908013775',
    projectId: 'prime-art-eab7d',
    storageBucket: 'prime-art-eab7d.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHLDFhUhrAdcb3O7nxcNNbXiIjXLon_wk',
    appId: '1:605908013775:web:6f599a85a6d0e46175ddba',
    messagingSenderId: '605908013775',
    projectId: 'prime-art-eab7d',
    authDomain: 'prime-art-eab7d.firebaseapp.com',
    storageBucket: 'prime-art-eab7d.firebasestorage.app',
    measurementId: 'G-313VFTSWMB',
  );
}
